ALTER TABLE twt_notification ADD COLUMN updated_at datetime ON UPDATE CURRENT_TIMESTAMP();
ALTER TABLE twt_specialnews ADD COLUMN updated_at datetime ON UPDATE CURRENT_TIMESTAMP();
ALTER TABLE twt_specialnews CHANGE summary summary VARCHAR(100) NULL;
ALTER TABLE twt_commonfiles ADD COLUMN updated_at datetime ON UPDATE CURRENT_TIMESTAMP();
ALTER TABLE twt_applicant_articlelist ADD COLUMN updated_at datetime ON UPDATE CURRENT_TIMESTAMP();
ALTER TABLE twt_applicant_articlelist ADD COLUMN created_at datetime ;
ALTER TABLE twt_applicant_exerciselist ADD COLUMN updated_at datetime ON UPDATE CURRENT_TIMESTAMP();
ALTER TABLE twt_applicant_exerciselist ADD COLUMN created_at datetime ;
ALTER TABLE twt_applicant_testlist ADD COLUMN updated_at datetime ON UPDATE CURRENT_TIMESTAMP();
ALTER TABLE twt_cert ADD COLUMN updated_at datetime ON UPDATE CURRENT_TIMESTAMP();
ALTER TABLE twt_applicant_entryform  ADD COLUMN updated_at datetime ON UPDATE CURRENT_TIMESTAMP();
ALTER TABLE twt_certlost  ADD COLUMN updated_at datetime ON UPDATE CURRENT_TIMESTAMP();
ALTER TABLE twt_complain  ADD COLUMN updated_at datetime ON UPDATE CURRENT_TIMESTAMP();
ALTER TABLE twt_student_info  ADD COLUMN updated_at datetime ON UPDATE CURRENT_TIMESTAMP();
ALTER TABLE twt_academy_testlist ADD COLUMN updated_at datetime ON UPDATE CURRENT_TIMESTAMP();
ALTER TABLE twt_academy_entryform  ADD COLUMN updated_at datetime ON UPDATE CURRENT_TIMESTAMP();
ALTER TABLE twt_probationary_trainlist ADD COLUMN updated_at datetime ON UPDATE CURRENT_TIMESTAMP();
ALTER TABLE twt_probationary_courselist  ADD COLUMN updated_at datetime ON UPDATE CURRENT_TIMESTAMP();
ALTER TABLE twt_probationary_entryform  ADD COLUMN updated_at datetime ON UPDATE CURRENT_TIMESTAMP();
ALTER TABLE twt_probationary_childentryform  ADD COLUMN updated_at datetime ON UPDATE CURRENT_TIMESTAMP();
ALTER TABLE twt_partybranch   ADD COLUMN updated_at datetime ON UPDATE CURRENT_TIMESTAMP();
ALTER TABLE b_userinfo   ADD COLUMN updated_at datetime ON UPDATE CURRENT_TIMESTAMP();
ALTER TABLE twt_logincount   ADD COLUMN updated_at datetime ON UPDATE CURRENT_TIMESTAMP();
ALTER TABLE twt_probationary_entryform ADD COLUMN isdeleted INT(5) DEFAULT 0;
ALTER TABLE twt_probationary_childentryform  ADD COLUMN isdeleted INT(5) DEFAULT 0;
ALTER TABLE twt_partybranch CHANGE partybranch_total_reply partybranch_total_reply INT(11) NOT NULL DEFAULT 0;
ALTER TABLE twt_partybranch CHANGE partybranch_total_topic partybranch_total_topic INT(11) NOT NULL DEFAULT 0;
ALTER TABLE twt_partybranch CHANGE partybranch_total_act partybranch_total_act INT(11) NOT NULL DEFAULT 0;
ALTER TABLE twt_logincount  ADD COLUMN created_at datetime ;