<?php
/**
 * Created by PhpStorm.
 * User: Kai.Z
 * Date: 2018/5/19
 * Time: 0:52
 */

namespace App\Http\Service\PartyStatus;



use App\Models\StudentInfo;
//成为积极分子
class Activity extends BaseWorkItem
{
    public function to()
    {
        if ($this->isActive())
            return;
        parent::to(); // TODO: Change the autogenerated stub


        StudentInfo::updateMainStatusTo($this->userNumber, MainStatus::ACTIVIST);
    }

    public function cancel()
    {
        if (!$this->isActive())
            return;
        parent::cancel(); // TODO: Change the autogenerated stub

        StudentInfo::updateMainStatusTo($this->userNumber, MainStatus::COMMUNIST_MEMBER_RECOMMENDATION);
    }

    public function isActive()
    {
        // TODO: Implement isActive() method.
        $status = StudentInfo::getMainStatus($this->userNumber);
        return $status == MainStatus::ACTIVIST || ($status >= MainStatus::DEVELOPMENT_TARGET && $status != MainStatus::COMMUNIST_MEMBER_RECOMMENDATION && $status != MainStatus::MEMBER_RECOMMENDATION);
    }
}