<?php
/**
 * Created by PhpStorm.
 * User: Kai.Z
 * Date: 2018/5/19
 * Time: 0:09
 */

namespace App\Http\Service\PartyStatus;


use App\Models\StudentInfo;
//团支部推优
class Communist extends BaseWorkItem
{
    public function to()
    {
        if ($this->isActive())
            return;
        parent::to(); // TODO: Change the autogenerated stub

        $status = StudentInfo::getMainStatus($this->userNumber);
        //党员推荐和团支部推优平级
        //如果已经被党员推荐了，则直接成为团推优+党员推荐
        if ($status == MainStatus::MEMBER_RECOMMENDATION){
            StudentInfo::updateMainStatusTo($this->userNumber, MainStatus::COMMUNIST_MEMBER_RECOMMENDATION);
        }
        else{
            StudentInfo::updateMainStatusTo($this->userNumber, MainStatus::COMMUNIST);
        }

    }

    public function cancel()
    {
        if (!$this->isActive())
            return;
        parent::cancel(); // TODO: Change the autogenerated stub

        $status = StudentInfo::getMainStatus($this->userNumber);
        //如果已经被党员推荐了，cancel团支部推优后还是党员推荐状态，否则直接退回到申请人
        if ($status == MainStatus::MEMBER_RECOMMENDATION){
            StudentInfo::updateMainStatusTo($this->userNumber, MainStatus::MEMBER_RECOMMENDATION);
        }
        else{
            StudentInfo::updateMainStatusTo($this->userNumber, MainStatus::APPLICANT);
        }
    }

    public function isActive()
    {
        // TODO: Implement isActive() method.
        $status = StudentInfo::getMainStatus($this->userNumber);
        return $status >= MainStatus::COMMUNIST || $status == MainStatus::ACTIVIST;
    }
}