<?php
/**
 * Created by PhpStorm.
 * User: Kai.Z
 * Date: 2018/5/19
 * Time: 0:25
 */

namespace App\Http\Service\PartyStatus;


use App\Models\StudentInfo;
//党员推荐
class MemberRecommendation extends BaseWorkItem
{
    public function to()
    {
        if ($this->isActive())
            return;
        parent::to(); // TODO: Change the autogenerated stub

        //党员推荐和团支部推优平级
        //如果已经被团推优了，则直接成为团推优+党员推荐
        $status = StudentInfo::getMainStatus($this->userNumber);
        if ($status == MainStatus::COMMUNIST){
            StudentInfo::updateMainStatusTo($this->userNumber, MainStatus::COMMUNIST_MEMBER_RECOMMENDATION);
        }
        else{
            StudentInfo::updateMainStatusTo($this->userNumber, MainStatus::MEMBER_RECOMMENDATION);
        }
    }

    public function cancel()
    {
        if (!$this->isActive())
            return;
        parent::cancel(); // TODO: Change the autogenerated stub

        $status = StudentInfo::getMainStatus($this->userNumber);
        //如果已经被团推优了，cancel党员推荐后还是团推优状态，否则直接退回到申请人
        if ($status == MainStatus::COMMUNIST){
            StudentInfo::updateMainStatusTo($this->userNumber, MainStatus::COMMUNIST);
        }
        else{
            StudentInfo::updateMainStatusTo($this->userNumber, MainStatus::APPLICANT);
        }
    }

    public function isActive()
    {
        // TODO: Implement isActive() method.
        $status = StudentInfo::getMainStatus($this->userNumber);
        return $status == MainStatus::MEMBER_RECOMMENDATION || $status == MainStatus::ACTIVIST || $status >= MainStatus::DEVELOPMENT_TARGET;
    }
}